// Tipos del dominio. Aqui no hay logica: solo interfaces, tipos y listas de valores.
export type {
  Id,
  IdAcontecimiento,
  IdComarca,
  IdContrato,
  IdFeria,
  IdJugador,
  IdMercado,
  IdObra,
  IdOrden,
  IdPartida,
  IdRebanyo,
  IdRecua,
} from './ids.ts';
export { idDeMercadoDeFeria, idDeMercadoLocal } from './ids.ts';
export { RECURSOS, RECURSOS_PERECEDEROS } from './recursos.ts';
export type { Recurso, Recursos } from './recursos.ts';
export { POTENCIALES, RASGOS, TERRENOS, VOLUMENES_FERIA } from './mundo.ts';
export type {
  Camino,
  ComarcaMundo,
  Coordenada,
  Feria,
  Localidad,
  Mundo,
  NivelPotencial,
  Potencial,
  Punto,
  Rasgo,
  Terreno,
  VolumenFeria,
} from './mundo.ts';
export {
  CARGAS_FISCALES,
  COMETIDOS,
  FUENTES_DE_PRECIOS,
  FUEROS,
  MODOS_DE_PARTIDA,
  NIVELES_DE_CONOCIMIENTO,
  RECURSOS_AGOTABLES,
  TIPOS_DE_OBRA,
} from './estado.ts';
export type {
  Acontecimiento,
  CargaFiscal,
  Cometido,
  ConfiguracionPartida,
  Conocimiento,
  DatosConocidos,
  EfectoAcontecimiento,
  EstadoComarca,
  EstadoJugador,
  EstadoMercado,
  EstadoPartida,
  FuenteDePrecios,
  Fuero,
  ModoDePartida,
  NivelDeConocimiento,
  Obra,
  PreciosConocidos,
  PuestoEnLaClasificacion,
  Rebanyo,
  Recua,
  RecursoAgotable,
  RegistroDeJugador,
  SituacionMovil,
  TipoDeObra,
} from './estado.ts';
export { ESTADOS_DE_ORDEN, TIPOS_DE_ORDEN } from './ordenes.ts';
export type {
  AccionDeMayordomo,
  CondicionDeMayordomo,
  EstadoDeOrden,
  Orden,
  OrdenBase,
  OrdenCarga,
  OrdenCometido,
  OrdenConstruir,
  OrdenDerribar,
  OrdenFormarRebanyo,
  OrdenFormarRecua,
  OrdenIncorporar,
  OrdenMayordomo,
  OrdenMercado,
  OrdenObraMayor,
  OrdenPolitica,
  OrdenRoturar,
  OrdenRuta,
  OrdenTradicion,
  OrdenTrasladarCorte,
  ParadaDeRuta,
  ReglaDeMayordomo,
  TipoDeOrden,
} from './ordenes.ts';
export {
  CALIDADES_CAMINO,
  CASAS,
  COMPOSICION_DE_MODIFICADORES,
  CRITERIOS_DE_TRADICION,
  ESTACIONES,
  HITOS,
  RONDAS_DE_TRADICION,
  TIPOS_DE_EDIFICIO,
  VERSION_REGLAS,
} from './reglas.ts';
export type {
  Casa,
  DatosCasa,
  DatosEdificio,
  DatosArranque,
  DatosCometidos,
  DatosConsumo,
  DatosTerritorio,
  DatosObraMayor,
  DatosObras,
  DatosFuero,
  DatosEstaciones,
  DatosProduccion,
  DatosInfluencia,
  DatosMercado,
  DatosMovimiento,
  DatosPoblacion,
  DatosPrestigio,
  DatosRecurso,
  DatosTradicion,
  CalidadCamino,
  ComposicionDeModificador,
  CondicionDeRonda,
  CriterioDeTradicion,
  DatosHito,
  Hito,
  Estacion,
  Modificadores,
  Permisos,
  Prohibiciones,
  RondaDeTradicion,
  TablasDeReglas,
  TipoEdificio,
  TipoObraMayor,
  Tradicion,
} from './reglas.ts';
export { NOMBRES_DE_FASE, SECCIONES_DE_CRONICA } from './cronica.ts';
export type {
  Cronica,
  EntradaDeCronica,
  NombreFase,
  Plantilla,
  PlantillaDeSuceso,
  SeccionDeCronica,
  Suceso,
} from './cronica.ts';
