// Los dieciseis edificios del juego (docs/03-economia.md §3.3). Una fila por edificio: coste, turnos
// de obra, lo que produce y consume por nivel, y la gente que necesita para trabajarlo.
import type { Recursos } from '../tipos/recursos.ts';
import type { DatosEdificio, TipoEdificio } from '../tipos/reglas.ts';

function coste(parte: Partial<Record<keyof Recursos, number>>): Recursos {
  return { pan: 0, madera: 0, piedra: 0, maravedis: 0, sal: 0, hierro: 0, lana: 0, ...parte };
}

/** Vecinos que trabaja cada nivel de una explotacion (docs/03 §3.4). */
const TRABAJO = 8;

export const EDIFICIOS: Readonly<Record<TipoEdificio, DatosEdificio>> = {
  granja: {
    nombre: 'Granja',
    potencial: 'labor',
    potencialMinimo: 1,
    coste: coste({ madera: 20, maravedis: 10 }),
    turnos: 2,
    nivelMaximo: 4,
    produccion: { pan: 10 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  huerta: {
    nombre: 'Huerta',
    potencial: 'labor',
    potencialMinimo: 2,
    coste: coste({ madera: 10, maravedis: 15 }),
    turnos: 2,
    nivelMaximo: 2,
    produccion: { pan: 6 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  molino: {
    nombre: 'Molino',
    potencial: 'labor',
    potencialMinimo: 1,
    coste: coste({ madera: 30, piedra: 10 }),
    turnos: 3,
    nivelMaximo: 2,
    produccion: {},
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: 'granja',
    esDePiedra: true,
    exigePermiso: null,
  },
  granero: {
    nombre: 'Granero',
    potencial: null,
    potencialMinimo: 0,
    coste: coste({ madera: 15, piedra: 20 }),
    turnos: 3,
    nivelMaximo: 1,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: true,
    exigePermiso: null,
  },
  aserradero: {
    nombre: 'Aserradero',
    potencial: 'monte',
    potencialMinimo: 1,
    coste: coste({ madera: 10, piedra: 10, maravedis: 10 }),
    turnos: 2,
    nivelMaximo: 4,
    produccion: { madera: 6 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  carbonera: {
    nombre: 'Carbonera',
    potencial: 'monte',
    potencialMinimo: 2,
    coste: coste({ madera: 15, maravedis: 10 }),
    turnos: 2,
    nivelMaximo: 2,
    produccion: {},
    consumo: { madera: 4 },
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  cantera: {
    nombre: 'Cantera',
    potencial: 'piedra',
    potencialMinimo: 1,
    coste: coste({ madera: 20, maravedis: 15 }),
    turnos: 3,
    nivelMaximo: 4,
    produccion: { piedra: 6 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  ferreria: {
    nombre: 'Ferreria',
    potencial: 'hierro',
    potencialMinimo: 2,
    coste: coste({ madera: 25, piedra: 20, maravedis: 30 }),
    turnos: 4,
    nivelMaximo: 3,
    produccion: { hierro: 4 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: 'carbonera',
    esDePiedra: true,
    exigePermiso: null,
  },
  salina: {
    nombre: 'Salina',
    potencial: 'sal',
    potencialMinimo: 1,
    coste: coste({ madera: 20, maravedis: 25 }),
    turnos: 3,
    nivelMaximo: 3,
    produccion: { sal: 5 },
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  majada: {
    nombre: 'Majada',
    potencial: 'pasto',
    potencialMinimo: 1,
    coste: coste({ madera: 15, maravedis: 10 }),
    turnos: 2,
    nivelMaximo: 3,
    produccion: {},
    consumo: {},
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  lonja: {
    nombre: 'Lonja de pescado',
    potencial: 'pesca',
    potencialMinimo: 1,
    coste: coste({ madera: 20, maravedis: 15 }),
    turnos: 2,
    nivelMaximo: 2,
    produccion: { pan: 6 },
    consumo: { sal: 2 },
    vecinosPorNivel: TRABAJO,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  mercado: {
    nombre: 'Mercado',
    potencial: null,
    potencialMinimo: 0,
    coste: coste({ madera: 15, piedra: 15, maravedis: 20 }),
    turnos: 3,
    nivelMaximo: 2,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: true,
    exigePermiso: null,
  },
  venta: {
    nombre: 'Venta',
    potencial: null,
    potencialMinimo: 0,
    coste: coste({ madera: 10, piedra: 10 }),
    turnos: 2,
    nivelMaximo: 1,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  casas: {
    nombre: 'Casas',
    potencial: null,
    potencialMinimo: 0,
    coste: coste({ madera: 25, piedra: 10 }),
    turnos: 2,
    nivelMaximo: 3,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: false,
    exigePermiso: null,
  },
  cerca: {
    nombre: 'Cerca',
    potencial: null,
    potencialMinimo: 0,
    coste: coste({ piedra: 20 }),
    turnos: 3,
    nivelMaximo: 1,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: true,
    exigePermiso: null,
  },
  // La acequia menor de los hortelanos: una obra corta que riega la comarca y le quita a su pan el
  // factor de la estacion. Sin permiso de casa no se puede levantar (docs/04 §4.1.8).
  acequia: {
    nombre: 'Acequia menor',
    potencial: 'labor',
    potencialMinimo: 1,
    coste: coste({ madera: 10, piedra: 15, maravedis: 10 }),
    turnos: 2,
    nivelMaximo: 1,
    produccion: {},
    consumo: {},
    vecinosPorNivel: 0,
    requiereEdificio: null,
    esDePiedra: true,
    exigePermiso: 'acequiaMenor',
  },
};
